version: "3.7"

volumes:
    #volumeはホストにコピー or 表示させないもの
    ##バイナリファイル（node_module）など、OS依存があるもの

    #node_moduleを入れるvolume
    vue-cli-node-volume:

services:
  app:
    image: testapp:1
    command: bash -c "cd webpackapp ; npm run dev"
    build: 
      context:  ./.docker
      dockerfile: Dockerfile
    container_name: testapp
    ports:
      - "18082:8080"
    volumes:
    #node_moduleを入れるボリューム
    - vue-cli-node-volume:/app/node_modules

    #コンテナ内の指定ディレクトリをホスト側と同期
    - .:/app
    stdin_open: true
    tty:  true